Revert tensorflow: 1.15.0 -> 1.12.0
The upgrade broke a test in ImageJ-TensorFlow:

  Error:  runLabelImageCommand(net.imagej.tensorflow.demo.LabelImageTest)  Time elapsed: 12.624 s  <<< ERROR!
  java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw error
    at net.imagej.tensorflow.demo.LabelImageTest.runLabelImageCommand(LabelImageTest.java:50)
  Caused by: java.lang.RuntimeException: Module threw error
  Caused by: java.lang.IncompatibleClassChangeError: Found interface org.tensorflow.OperationBuilder, but class was expected

The upgrade is not urgent, so for now we revert to the working version.