CI: call apt-get update before install
Hoping to avoid errors like:

  Ign:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libxml2-utils amd64 2.9.13+dfsg-1ubuntu0.1
  Err:8 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libxml2-utils amd64 2.9.13+dfsg-1ubuntu0.1
    404  Not Found [IP: 52.252.75.106 80]
  Fetched 2359 kB in 0s (10.1 MB/s)
  E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2-utils_2.9.13%2bdfsg-1ubuntu0.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
  E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
  Error: Process completed with exit code 100.