mega-melt: skip imagej-legacy and n5-zarr tests
The current version of imagej-legacy fails the melt with errors like:

    Error:  testCanConvert2(net.imagej.legacy.convert.StringToImagePlusConverterTest)  Time elapsed: 3.731 s  <<< ERROR!
    java.awt.HeadlessException:

    No X11 DISPLAY variable was set, but this program performed an operation which requires it.
            at net.imagej.legacy.convert.StringToImagePlusConverterTest.setUp(StringToImagePlusConverterTest.java:75)

Once imagej/imagej-legacy#285 is fixed, we can reenable it.

And n5-zarr has a failing test due to changes in n5 as of version 2.5.0.
When saalfeldlab/n5-zarr#11 is merged and released, we can reenable it.